fix: test workflow

diff --git a/.github/workflows/_test-workflow.yml b/.github/workflows/_test-workflow.yml
--- a/.github/workflows/_test-workflow.yml
+++ b/.github/workflows/_test-workflow.yml
@@ -13,11 +13,48 @@ on:
 
 jobs:
   test:
-    uses: ./.github/workflows/foundry-test.yml
-  test-zksync:
-    uses: ./.github/workflows/foundry-test.yml
-    with:
-      zksync: true
+    name: Foundry build n test
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          submodules: recursive
+
+      - uses: bgd-labs/action-rpc-env@main
+        with:
+          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
+
+      # we simply use foundry zk for all jobs in this repo
+      - name: Run Foundry setup
+        uses: ./.github/actions/foundry-setup@main
+        with:
+          ZKSYNC: "true"
+
+      - name: Run Forge tests
+        id: test
+        uses: ./.github/actions/foundry-test@main
+
+      - name: Run ZK tests
+        id: zktest
+        uses: ./.github/actions/foundry-test@main
+        with:
+          ZKSYNC: true
+
+      - name: Run Gas report
+        uses: ./.github/actions/foundry-gas-report@main
+
+      - name: Run Lcov report
+        uses: ./.github/actions/foundry-lcov-report@main
+
+      - name: Run Forge tests
+        uses: ./.github/actions/comment-artifact@main
+
+      # we let failing tests pass so we can log them in the comment, still we want the ci to fail
+      - name: Post test
+        if: ${{ steps.test.outputs.testStatus != 0 || steps.zktest.outputs.testStatus != 0 }}
+        run: |
+          echo "tests failed"
+          exit 1
   release:
     needs: [test]
     uses: ./.github/workflows/release.yml
