fix: resolve deprecations (#13)
* fix: resolve deprecations

* test: remove artifact replacement

* test: arg

* test: next test

* fix: test workflow

* fix: test

* fix: syntax

* fix: test

* fix: try if this works

* fix: test new version

* fix: properly escape chars again

* fix: ...

* fix: last test

* fix: fuck this is surrender

* fix: preescape

* :shrug:

* fix: use printf

* fix: try one last thing

diff --git a/.github/workflows/foundry-test.yml b/.github/workflows/foundry-test.yml
--- a/.github/workflows/foundry-test.yml
+++ b/.github/workflows/foundry-test.yml
@@ -48,15 +48,6 @@ jobs:
         run: |
           cp .env.example .env 2> /dev/null || :
 
-      - uses: actions/cache@v3
-        with:
-          path: |
-            out/
-            cache/
-            ~/.foundry/cache/
-          key: ${{ runner.os }}-foundry-${{ github.sha }}
-          restore-keys: ${{ runner.os }}-foundry-
-
       - name: Run Forge build
         run: |
           forge --version | tee /tmp/foundry_version ; test ${PIPESTATUS[0]} -eq 0
@@ -67,21 +58,16 @@ jobs:
       - name: Run Forge tests
         run: |
           ${{ inputs.testCommand }} | tee /tmp/foundry_test
-          echo "::set-output name=testStatus::${PIPESTATUS[0]}"
+          echo "testStatus=${PIPESTATUS[0]}" >> $GITHUB_ENV
         id: test
 
-      # comment on pr
-      - id: get-comment-body
+      - name: Create comment body
+        id: get-comment-body
         run: |
-          printf "Foundry report\n\n" > /tmp/report.txt
-          printf "\`\`\`shell\n$(cat /tmp/foundry_version)\n\`\`\`\n\n" >> /tmp/report.txt
-          printf "<details><summary>Build log</summary>\n\n\`\`\`shell\n$(cat /tmp/foundry_build)\n\`\`\`\n</details>\n\n" >> /tmp/report.txt
-          printf "<details><summary>Test ${{ steps.test.outputs.testStatus == 0 && 'success :rainbow:' || 'error :finnadie::x:'}}</summary>\n\n\`\`\`shell\n$(cat /tmp/foundry_test)\n\`\`\`\n</details>"  >> /tmp/report.txt
-          body="$(cat /tmp/report.txt | sed -r 's/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g')"
-          body="${body//'%'/'%25'}"
-          body="${body//$'\n'/'%0A'}"
-          body="${body//$'\r'/'%0D'}" 
-          echo "::set-output name=body::$body"
+          printf "Foundry report\n\n" > /tmp/template.md
+          printf "\`\`\`shell\n$(cat /tmp/foundry_version)\n\`\`\`\n\n" >> /tmp/template.md
+          printf "<details><summary>Build log</summary>\n\n\`\`\`shell\n$(cat /tmp/foundry_build)\n\`\`\`\n</details>\n\n" >> /tmp/template.md
+          printf "<details><summary>Test ${{ env.testStatus == 0 && 'success :rainbow:' || 'error :finnadie::x:'}}</summary>\n\n\`\`\`shell\n$(cat /tmp/foundry_test)\n\`\`\`\n</details>\n\n" >> /tmp/template.md
 
       - name: Find Comment
         uses: peter-evans/find-comment@v2
@@ -100,12 +86,12 @@ jobs:
         with:
           comment-id: ${{ steps.fc.outputs.comment-id }}
           issue-number: ${{ github.event.pull_request.number }}
-          body: ${{ steps.get-comment-body.outputs.body }}
+          body-file: /tmp/template.md
           edit-mode: replace
 
       # we let failing tests pass so we can log them in the comment, still we want the ci to fail
       - name: Post test
-        if: ${{ steps.test.outputs.testStatus != 0 }}
+        if: ${{ env.testStatus != 0 }}
         run: |
           echo "tests failed"
           exit 1
