fix: error on error and report test status in comment (#4)

diff --git a/.github/workflows/foundry-test.yml b/.github/workflows/foundry-test.yml
--- a/.github/workflows/foundry-test.yml
+++ b/.github/workflows/foundry-test.yml
@@ -27,16 +27,14 @@ jobs:
 
       - name: Run Forge build
         run: |
-          forge --version | tee /tmp/foundry_version
-          forge build --sizes | tee /tmp/foundry_build
-          echo $build
-          echo "::set-output name=version::$version"
-          echo "::set-output name=build::$build"
+          forge --version | tee /tmp/foundry_version ; test ${PIPESTATUS[0]} -eq 0
+          forge build --sizes | tee /tmp/foundry_build ; test ${PIPESTATUS[0]} -eq 0
         id: build
 
       - name: Run Forge tests
         run: |
           ${{ inputs.testCommand }} | tee /tmp/foundry_test
+          echo "::set-output name=testStatus::${PIPESTATUS[0]}"
         id: test
 
       # comment on pr
@@ -45,7 +43,7 @@ jobs:
           printf "Foundry report\n\n" > /tmp/report.txt
           printf "\`\`\`shell\n$(cat /tmp/foundry_version)\n\`\`\`\n\n" >> /tmp/report.txt
           printf "\`\`\`shell\n$(cat /tmp/foundry_build)\n\`\`\`\n\n" >> /tmp/report.txt
-          printf "<details><summary>Test</summary>\n\n\`\`\`shell\n$(cat /tmp/foundry_test)\n\`\`\`\n</details>"  >> /tmp/report.txt
+          printf "<details><summary>Test ${{ steps.test.outputs.testStatus == 0 && 'success :rainbow:' || 'error :finnadie::x:'}}</summary>\n\n\`\`\`shell\n$(cat /tmp/foundry_test)\n\`\`\`\n</details>"  >> /tmp/report.txt
           body="$(cat /tmp/report.txt | sed -r 's/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g')"
           body="${body//'%'/'%25'}"
           body="${body//$'\n'/'%0A'}"
@@ -67,3 +65,10 @@ jobs:
           issue-number: ${{ github.event.pull_request.number }}
           body: ${{ steps.get-comment-body.outputs.body }}
           edit-mode: replace
+
+      # we let failing tests pass so we can log them in the comment, still we want the ci to fail
+      - name: Post test
+        if: ${{ steps.test.outputs.testStatus == 1 }}
+        run: |
+          echo "tests failed"
+          exit 1
